Domain/Scheduling/EventSourcedRepositoryExtensions.cs

Was just poking around your implementation of command scheduling and noticed this.  Are there side effects to the op that I might be overlooking?

remove needless use of multiplicative identity op

---

Domain/Scheduling/EventSourcedRepositoryExtensions.cs

I think this is a left over problem with the TPL and scheduling commands. ApplyAsync should be used everywhere by default now no?

Apply scheduled commands async

---

Domain/Authorization/AuthorizationFor.cs

The dynamic object in this method caused a first chance exception, Microsoft.CSharp.RuntimeBinder.RuntimeBinderException. Although the exception is caught and handled, it slows down debug a lot. So we removed the dynamic object here.

not using dynamic object for ToApplyAnyCommand.Requires

---

AssemblyInfoVersion.cs
Domain.Api/Microsoft.Its.Domain.Api.nuspec
Domain.Sql/Microsoft.Its.Domain.Sql.nuspec
Domain.Testing/Microsoft.Its.Domain.Testing.nuspec
Domain/Microsoft.Its.Domain.nuspec
Its.Cqrs.sln
buildNuget.ps1

NuGet can get it from assembly metadata, looking at the `AssemblyInformationalVersion` attribute.

Consolidate NuGet package version specifications

---

AssemblyInfoVersion.cs
Domain.Api/Microsoft.Its.Domain.Api.nuspec
Domain.Sql/DbContextExtensions.cs
Domain.Sql/Microsoft.Its.Domain.Sql.nuspec
Domain.Testing/Microsoft.Its.Domain.Testing.nuspec
Recipes/Its.Domain.ServiceBusCommandScheduling.nuspec

With Azure SQL DB V12, the database creation SQL command is blocked until the creation is finished. So increase the SQL command timeout to 10 minutes.

Increase create database sql script timeout to 10 minutes

---

Domain.Sql/ReadModelUpdate.cs
Domain/Serialization/Serializer.cs

- Remove SerializedEvent from ReadModelInfo.Error column. Use FailedOnEventId = EventHandlingErrors.OriginalId to find the full details. This has the benefit of making the Error column in both tables have the same shape.
- Make ToDiagnosticJson() tolerate exceptions.
- Switch from ToJson() to ToDiagnosticJson() for recording exceptions, since ToJson() doesn't (and shouldn't) tolerate exceptions.
- Let Log.Write() handle the details of how it serializes for logging

Fix serialization error when recording projection errors

---

AssemblyInfoVersion.cs
Domain.Api/Microsoft.Its.Domain.Api.nuspec
Domain.Sql/Microsoft.Its.Domain.Sql.nuspec
Domain.Testing/Microsoft.Its.Domain.Testing.nuspec
Domain/EventSourcedAggregate.cs
Recipes/Its.Domain.ServiceBusCommandScheduling.nuspec

This breaks compatibility with existing clients.
commit 237cd3148ee19e8211a3fee6cb928bc501b197d7
Author: jonsequitur <jonsequeira@gmail.com>
Date:   Wed Aug 26 15:18:26 2015 -0700

Revert 237cd31 - "make EventSourcedAggregate.ETags internal"

---

Domain/SystemClock.cs

This is because some of code uses Month, Year properties of DateTimeOffset. At the end of month, the Month, Year properties will be different between DateTimeOffset.Now and DateTimeOffset.UtcNow.

Update the systemclock to use UtcNow. 

---

Domain.Sql/EventHandlerProgressCalculator.cs
Domain.Sql/ReadModelUpdate.cs
Domain.Sql/SqlEventSourcedRepository{T}.cs

removing manual handling of the Transaction scope related to EF operations. this is required because EF execution strategies (sqlAzure specifically) doesnt let you control the transaction scope yourself.
details here: http://go.microsoft.com/fwlink/?LinkId=309381

Remove transaction scope handling

---

Domain.Sql/Microsoft.Its.Domain.Sql.nuspec

Raising the minimum version of Entity Framework required from 6.0 to 6.1.3.

Update Domain.Sql nuspec EF version

---

Domain.Tests/MarcoPolo.cs
Domain/EventSourcedAggregate{T}.cs
Sample.Domain/Ordering/Order.EnactCommand.cs
Samples/Banking/Banking.Domain/CheckingAccount/Events/CheckingAccount.FundsWithdrawn.cs

as shown in the MarcoPolo.cs class i altered below i felt this flowed a bit better and reduced the need for as much boiler plate code.
thoughts?
also set a property that wasn't being set in the bank example.

change RecordEvent to return the event rather than void

---

Domain.Sql/Migrations/EventStoreDbContext-0_14_0.sql

Looking at query plans with Chris, including StreamName in the index resulted in being able to go entirely off of the index for the catchup query.

Changing [IX_Id_and_Type] to include StreamName

---

.gitignore
Domain.Sql.Tests/DatabaseSetupAndMigrationTests.cs
Domain.Sql/CreateAndMigrate{T}.cs
Domain.Sql/ExclusiveEventStoreCatchupQuery.cs

- Added support to skip migrations on read-only connections
- Optimized the SQL for ExclusiveEventStoreCatchupQuery and made it easier to read
- Updated .gitignore to exclude ".vs" for VS2015 and "TestResults"
- Added .gitattributes to address line endings

Read-Only Connection Detection and Catchup Query Optimization

---

Domain.Sql.Tests/DatabaseSetupAndMigrationTests.cs
Domain.Sql.Tests/Domain.Sql.Tests.csproj
Domain.Sql.Tests/EventStoreDbTest.cs
Domain.Sql.Tests/ReadModelCatchupRollingCatchupTests.cs
Domain.Sql.Tests/ReadModelCatchupTests.cs
Domain.Sql.Tests/packages.config
Domain.Tests/ConfigurationTests.cs
Domain.Tests/ObjectIdTests.cs
Domain/Serialization/PrimitiveConverter.cs

NewtonSoft.Json configuration to simplify `ObjectId<T>`'s serialized form was throwing when deserializing `ObjectId<Guid>`. This fixes it.

Object id serialization fix

---

Domain.Sql/CommandScheduler/Storage.cs
Domain.Sql/CreateAndMigrate{T}.cs
Domain.Sql/DatabaseExtensions.cs
Domain.Sql/Migrations/Migrator.cs

Databases could not be created due to the password not being on the connection string, and also TransactionScopes were used. See commits for more details.

Fix Azure DB compatibility issues

---

Domain.Sql/Migrations/AzureSqlDbMigrator.cs

After the DbContext changes, this was not updated correctly to use the correct database string.

Fix AzureSqlDbMigrator to use the correct database string in SQL statement

---

AssemblyVersion.cs
Domain.Api/Domain.Api.nuspec
Domain.Sql/Domain.Sql.nuspec
Domain.Testing/Domain.Testing.nuspec
Domain.Tests/CommandContextTests.cs
Domain/CommandContext.cs

This corrects a regression that was introduced in 0.13.3-beta. This may affect commands that were scheduled without code to explicitly set their etags, i.e. using Its.Domain's default etag strategy. 
The impact will be a potential duplication on retry for some failed commands. A command will be affected if all of the following are true:
* The command was scheduled during handling of a scheduled command.
* Its etag was not explicitly set.
* It was originally scheduled using v0.13.3-beta.
* It failed on delivery and was set to be retried.
* The retry occurred using version 0.15.10-beta or later.

Fix NextETag regression

---

Domain.Api/Domain.Api.csproj
Domain.Sql/Domain.Sql.csproj
Domain.Testing/Domain.Testing.csproj
Domain/Domain.csproj

The release build is the one that AppVeyor builds. My goal in not turning this on in the debug build is to keep the developer experience as fast as possible.

treat compiler warnings as errors in the release build

---

Domain.Api.Tests/CommandDispatchTests.cs
Domain.Api/DomainApiController.cs
Domain.Sql.Tests/SqlCommandSchedulerClockTests.cs
Domain.Sql.Tests/SqlCommandSchedulerTests_EventSourced.cs
Domain.Sql.Tests/SqlCommandSchedulerTests_NonEventSourced.cs
Domain.Sql/CommandScheduler/SqlCommandSchedulerExtensions.cs
Domain.Sql/CommandScheduler/Storage.cs
Domain.Testing.Tests/ScenarioBuilderWithInMemoryEventStoreTests.cs
Domain.Testing.Tests/VirtualClockCommandSchedulingTests.cs
Domain.Testing/VirtualClock.cs
Domain.Tests/CommandContextTests.cs
Domain.Tests/CommandFailedTests.cs
Domain.Tests/CommandScheduled_T_Tests.cs
Domain.Tests/CommandSchedulerIdempotencyTests.cs
Domain.Tests/CommandSchedulerPipelineTests.cs
Domain.Tests/CommandSchedulingTests_EventSourced.cs
Domain.Tests/CommandSchedulingTests_NonEventSourced.cs
Domain.Tests/ConstructorCommandTests.cs
Domain.Tests/Domain.Tests.csproj
Domain.Tests/EventSourcedAggregateCommandTests.cs
Domain.Tests/EventSourcedCommandTarget.cs
Domain.Tests/NonEventSourcedCommandTargetTests.cs
Domain.Tests/ScheduledCommandTests.cs
Domain.Tests/ScheduledCommand_T_Tests.cs
Domain/ConstructorCommand{T}.cs
Domain/Scheduling/CommandScheduler.cs
Domain/Scheduling/ScheduledCommand{T}.cs
Test domains/Ordering.Domain/Ordering/Commands/CreateOrder.cs

This fixes issue #182 by enforcing that `TargetId` or `AggregateId` are passed to the constructor of `ConstructorCommand<T>`, and then enforcing in the constructor of `ScheduledCommand<T>`  that `ScheduledCommand<T>.TargetId` / `AggregateId` matches `ScheduledCommand<T>.TargetId` / `AggregateId`.
This isn't ideal but a cleaner approach will have to wait until strings become the default for identifiers for event sourced aggregates (#26).

Fix issue 182

---

Domain.Sql/ExclusiveEventStoreCatchupQuery.cs

Output the query that caused timeout to trace.

Output the query that caused timeout to trace.

---

Domain.Api.Tests/Properties/AssemblyInfo.cs
Domain.Sql.Tests/Properties/AssemblyInfo.cs
Domain.Sql/EventContractResolver.cs
Domain.Sql/EventExtensions.cs
Domain.Testing.Tests/Properties/AssemblyInfo.cs
Domain.Tests/Properties/AssemblyInfo.cs
Domain/Serialization/OptionalContractResolver.cs
Domain/Serialization/Serializer.cs
Test domains/Banking.Domain.Tests/Properties/AssemblyInfo.cs
appveyor.yml

fixes: https://github.com/jonsequitur/Its.Cqrs/issues/196
- Right now, we are blindly overwriting ContractResolver with a new instance of EventContractResolver
- Thus, if user specifies serialization settings, the ContractResolver piece of those settings are not being respected.  This is problematic if the ContractResolver is doing something important (e.g. overriding CreateConstructorParameters to deal with constructors)
- If the user specifies their own serialization settings, it's my belief that they should fully own the consequences (e.g. not serializing IPrincipal).  
- Extracting "rules" from EventContractResolver and OptionalContractResolver into callable methods enables users to incorporate these rules in their own contract resolver

Respect user-defined serialization settings

---

Domain.Api.Tests/Properties/AssemblyInfo.cs
Domain.Sql.Tests/Properties/AssemblyInfo.cs
Domain.Testing.Tests/Properties/AssemblyInfo.cs
Domain.Tests/Properties/AssemblyInfo.cs
Test domains/Banking.Domain.Tests/Properties/AssemblyInfo.cs
appveyor.yml

- By default, NUnit doesn't run tests in parallel within an assembly.  Removing AssemblyInfo.cs directives because those aren't (according to documentation) doing anything.  Those control the degree of parallelism for tests that opt-into parallelism
- NUnit does run tests across assemblies in parallel.  AppVeyor.yml now calls the NUnit CLI directly, setting agents=1 to disable that
- No longer using the "Previous" VS 2015 build image.  Now using the "current" one.
- Build still fails on a single unit test.  This same unit test consistently fails with different NUnit CLI arguments, so I think it might be a legitimate failure:
```
1) Error : Microsoft.Its.Domain.Sql.Tests.DiagnosticTests.Sensor_can_be_used_to_check_read_model_catchup_status
System.AggregateException : One or more errors …
```

disable parallelism across assemblies
